services:
  db:
    image: 'postgres:15.3'
    container_name: vacation-db
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - vacation

  api:
    depends_on:
      - 'db'
    restart: always
    build: ./backend
    container_name: vacation-api
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=db
    volumes:
      - ./backend:/app
    networks:
      - vacation

  frontend:
    build: ./frontend
    container_name: vacation-frontend
    volumes:
      - ./frontend:/app
    ports:
      - '5173:5173'
    depends_on:
      - api
    networks:
      - vacation

volumes:
  postgres:

networks:
  vacation:
    name: vacation_network
